export const ActionTypes = {
	MESSAGES: {
		GET_MESSAGES: 'GET_MESSAGES',
		GET_MESSAGES_REQUEST: 'GET_MESSAGES_REQUEST',
		GET_MESSAGES_SUCCESS: 'GET_MESSAGES_SUCCESS',
		GET_MESSAGES_FAIL: 'GET_MESSAGES_FAIL',

		ADD_NEW_MESSAGE: 'ADD_NEW_MESSAGE',
		ADD_NEW_MESSAGE_REQUEST: 'ADD_NEW_MESSAGE_REQUEST',
		ADD_NEW_MESSAGE_SUCCESS: 'ADD_NEW_MESSAGE_SUCCESS',
		ADD_NEW_MESSAGE_FAIL: 'ADD_NEW_MESSAGE_FAIL'
	}
};